config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users
  root to: 'pages#home'
  resources :profiles, only: [:index, :show, :new, :edit, :update] do
    resources :notes, only: [:new, :create, :show, :index]
  end
  resources :loans, only: [:new, :create, :show, :index] do
    resources :loanees, only: [:new, :create]
  end
  resources :loanees, only: [:show, :edit, :update] do
    resources :weekly_payments, only: [:new, :create, :index, :edit, :update]
  end
  resources :users, only: [:new, :index, :show]
  resources :weekly_payments, only: [:edit, :update]
  post 'user_profile', to: "users#create", as: 'user_profile'
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy
  has_one_attached :photo

  validates :village, presence: true
  validates :phone_number, presence: true
  validates :birthday, presence: true
  validates :join_date, presence: true
  validates :business_type, presence: true
  validates :photo, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :village, :business_type ],
    associated_against: {
      user: [ :first_name, :last_name, :email ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :set_profile, only: [:show, :edit, :update]
  def index
    if params[:query].present?
      @profiles = policy_scope(Profile).global_search(params[:query])
    else
      @profiles = Profile.all
      @profiles = policy_scope(Profile)
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'list.html', locals: { profiles: @profiles } }
    end
  end

  def show
    @user = User.new
    @weekly_payment = WeeklyPayment.new
  end

  def new
    @profile = Profile.new
    authorize @profile
  end

  def create
    @profile = Profile.new(profile_params)
    authorize @profile
    if @profile.save
      redirect_to profiles_show_path(@profile)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @profile.update(profile_params)
    authorize @profile
    if @profile.save
      redirect_to profile_path(@profile)
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:village, :phone_number, :birthday, :join_date, :business_type, :user_id)
  end

  def set_profile
    @profile = Profile.find(params[:id])
    authorize @profile
  end
end

app/views/profiles/_button_logic_show.html.erb
<% unless @profile.user.active_debt.nil? %>
  <% total = @profile.user.active_debt.total.to_f %>
  <% paid_sum = 0 %>
  <% @profile.user.active_debt.weekly_payments.each {|payment| paid_sum = paid_sum + payment.amount.to_f.round(2)} %>
  <% if @profile.user.active_debt &&  total - paid_sum > 0 %>
    <%#= link_to "Payment", new_loanee_weekly_payment_path(@profile.user.active_debt), class: "btn btn-large"  %>
    <%= render 'payment_popup', profile:@profile %>
    <%= link_to "History", loanee_weekly_payments_path(Loanee.find(@profile.user.active_debt.id)), class: "btn btn-large" %>
  <% elsif @profile.user.active_debt &&  total - paid_sum == 0%>
    <p class="mark-yellow" style="font-size: 24px"> This user has paid off the loan. </p>
  <% else %>
    <p class="mark-red mt-4 mr-4" style="font-size: 18px;color:white;height:100%;width:25%;"> This borrower has over-paid. </p>
    <%= link_to "History", loanee_weekly_payments_path(Loanee.find(@profile.user.active_debt.id)), class: "btn btn-large" %>
  <% end %>
<% else %>
<br>
  <p class="mark" style="text-align:center;"><small><i>This user has no active debts.</i></small> </p>
<% end %>

app/views/profiles/_form.html.erb
<%= simple_form_for @profile do |f| %>
  <%= f.input :village, label: 'Edit the village' %>
  <%= f.input :phone_number, label: 'Edit the phone number' %>
  <%= f.input :business_type, label: 'Edit the business_type' %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/profiles/_group.html.erb
<div class="card-group-container">
  <p><%= link_to "Go to Loan group", loan_path(@profile.user.debts.last.loan), class:"btn btn-primary round", style:"box-shadow: rgba(0, 0, 0, 0.16) 0px 1px 4px;border-radius: 16px;"%></p>
  <% @profile.user.debts.last.loan.loanees.each do |person| if person.user != @profile.user %>
  <div class="card-member">
    <%= cl_image_tag(person.user.profile.photo.key, gravity: "face", height: 240, width: 240, crop: 'fill') %>
    <div class="card-member-infos">
      <p><%= link_to person.user.full_name.titleize, profile_path(person.user.profile)  %></p>
    </div>
  </div>
<% end %>
<% end %>
</div>

app/views/profiles/_index_logic.html.erb
<% unless profile.user.active_debt.nil? %>
  <% total = profile.user.active_debt.total.to_f.round(2) %>
  <% paid_sum = 0 %>
  <% profile.user.active_debt.weekly_payments.each {|payment| paid_sum = paid_sum + payment.amount.to_f.round(2)} %>
  <% if profile.user.active_debt &&  total - paid_sum > 0 %>
    <%= link_to "View Group", loan_path(profile.user.active_debt.loan), class:'card-view-group-link' %>
  <% else %>
    <p class="card-view-group-link">No Active Loans</p>
  <% end %>
<% else %>
  <p class="card-view-group-link">No Active Loans</p>
<% end %>

app/views/profiles/_index_status.html.erb
<% unless profile.user.debts == []  %>
  <% case profile.user.debts.last
.status
           when 'active' %>
  <i class="fas fa-check-circle" style="color: #309C76"></i>
  <% when 'closed' %>
  <i class="fas fa-check-circle" style="color: #B7B5B3"></i>
  <% when 'default' %>
  <i class="fas fa-times-circle" style="color: #BA3B46"></i>
  <% when 'late' %>
  <i class="fas fa-clock" style="color: #DBAD6A"></i>
<% end %>
<% end %>

app/views/profiles/_payment_popup.html.erb
<button type="button" class="btn btn-large-green" data-toggle="modal" data-target="#exampleModal">
  Payment
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">How much money did you receive?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for  [@profile.user.active_debt, @weekly_payment] do |f| %>
        <%= f.input :amount, label: 'Enter amount', input_html: {value: "#{(@profile.user.debts.last.total.round(2) / @profile.user.debts.last.loan.weeks).round(2) }"} %>
        <%# <p id="sweet-alert-demo" class="btn btn-primary">Confirm</p> %>
        <%# <%= f.submit "", id:"confirm-link", class:"hidden" %>
        <%= f.submit "Confirm", class:"btn btn-primary" %>
        <% end %>
      </div>
      <div class="modal-footer" style="text-align:center;">
        <%# <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button> %>
          <p><small>Weekly payment for <%= @profile.user.first_name%> is <strong style="color:red;">$<%= (@profile.user.debts.last.total.to_f.round(2) / @profile.user.debts.last.loan.weeks).round(2) %></strong></small></p>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_profile_info.html.erb
<p><i class="fas fa-map-pin"></i>&nbsp;&nbsp;<%= profile.village %></p>
        <p><i class="fas fa-cash-register"></i>&nbsp;&nbsp;<%= profile.business_type.titleize %></p>
        <p><i class="fas fa-phone"></i>&nbsp;&nbsp;<%= profile.phone_number %></p>
        <p><i class="fas fa-birthday-cake"></i>&nbsp;&nbsp;<%= profile.birthday.strftime("%B %e, %Y") %></p>
        <p><i class="fas fa-file-signature"></i>&nbsp;&nbsp;<%= profile.join_date.strftime("%B %e, %Y") %></p>

app/views/profiles/_profiles.html.erb
      <% @profiles.each do |profile| %>
  <div class="col-sm-4">
    <div class="card-identity" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(profile.photo.key, width: 300, height: 300, crop: 'fill', gravity: :face, radius: 16, background:"#0000ffff") %>)">
      <div class="card-identity-content">
        <%= link_to '', profile_path(profile), class: 'card-link' %>
        <h2 class="card-name"><%= profile.user.full_name.titleize %></h2>
        <h3 class="card-village"><%= profile.village %></h3>
        <div class="card-identity-button">
          <%= render 'index_logic', profile: profile %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/_search.html.erb
<%= simple_form_for :query, url: profiles_path, method: :get do |f| %>
  <div class="search-form-control form-group" data-controller="refresh-list">
    <input class="form-control string required" type="text" name="query" id="search_query" placeholder="Find a loanee" data-refresh-list-target="searchInput" data-action="keyup->refresh-list#update"/>
    <button name="button" type="submit" class="btn btn-search">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col">
      <div data-controller="refresh-list">
        <%= form_with url: profiles_path, method: :get, html: { class: 'mb-5', data: { refresh_list_target: 'form' } } do |f| %>
          <%= f.text_field :query,
                     class: "form-control",
                     placeholder: 'Type name or village',
                     value: params[:query],
                     data: {
                      refresh_list_target: 'searchInput',
                    } %>
        <% end %>

app/views/profiles/_status.html.erb
<% case @profile.user.debts.last.status
           when 'active' %>
<i class="fas fa-check-circle" style="color: #478564"></i>
<% when 'closed' %>
<i class="fas fa-check-circle" style="color: #B7B5B3"></i>
<% when 'default' %>
<i class="fas fa-times-circle" style="color: #BA3B46"></i>
<% when 'late' %>
<i class="fas fa-clock" style="color: #DBAD6A"></i>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <h1>Edit Profile</h1>
  <%= render 'form', profile:@profile%>
  <%= link_to profile_path(@profile) do %>
    <i class="fas fa-long-arrow-alt-left fa-2x"></i>
  <% end %>
</div>

app/views/profiles/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <div data-controller="refresh-list">
        <%= form_with url: profiles_path, method: :get, html: { class: 'mb-5', data: { refresh_list_target: 'form' } } do |f| %>
          <%= f.text_field :query,
                           class: "form-control",
                           placeholder: 'Type name of person or village',
                           value: params[:query],
                           data: {
                            refresh_list_target: 'searchInput',
                            action: "keyup->refresh-list#update"
                          } %>
        <% end %>
        <%= render 'list', profiles: @profiles %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <%= render 'form', user: @user%>
</div>

app/views/profiles/show.html.erb
<div class="container mb-5">
  <%= simple_form_for :query, url: profiles_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="query" id="search_query" />
      <button name="button" type="submit" class="btn btn-search">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
  <% end %>
  <div class="card-profile">
    <div class="img-back">
      <div class="row d-flex justify-content-between px-3">
        <%= link_to profiles_path do %>
          <div><i class="fas fa-long-arrow-alt-left fa-2x"></i></div>
        <% end %>
        <%= link_to edit_profile_path(@profile) do %>
          <div><i class="fas fa-edit fa-2x"></i></div>
        <% end %>
      </div>
    </div>
    <div class="row d-flex">
      <div class="col-sm text-center">
        <%= cl_image_tag(@profile.photo.key, :transformation=>[{:gravity=>"face", :height=>240, :width=>240, :crop=>"fill"}, {:radius=>"max"}]) %>
        <h1><%= @profile.user.full_name.titleize %>
          <% unless @profile.user.debts==[] %>
            <%= render 'status' %></h1>
        <% end %>
        <div class="d-flex justify-content-center">
          <%= render 'button_logic_show', profile:@profile %>
          <% unless @profile.user.debts ==[] %>
            <p><%= link_to 'Notes', profile_notes_path(@profile), class:"btn btn-large"%></p>
          <% end %>
        </div>
      </div>
    </div>
    <% unless @profile.user.debts == [] %>
      <div class="d-flex justify-content-center">
        <div class="row d-flex ">
          <div class="col-4">
            <div class="card-text">
              <p><i class="fas fa-map-pin"></i>&nbsp;&nbsp;<%= @profile.village %></p>
              <p><i class="fas fa-cash-register"></i>&nbsp;&nbsp;<%= @profile.business_type.titleize %></p>
              <p><i class="fas fa-phone"></i>&nbsp;&nbsp;<%= @profile.phone_number %></p>
              <p><i class="fas fa-birthday-cake"></i>&nbsp;&nbsp;<%= @profile.birthday.strftime("%B %e, %Y") %></p>
              <p><i class="fas fa-file-signature"></i>&nbsp;&nbsp;<%= @profile.join_date.strftime("%B %e, %Y") %></p>
            </div>
          </div>
          <div class="col-8">
            <% unless @profile.user.active_debt.nil? %>
              <%= render 'group' %>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="row d-flex justify-content-around">
        <div><%= render 'profile_info', profile:@profile %></div>
        <div><%= link_to 'Notes', profile_notes_path(@profile), class:"btn btn-large"%></div>
      </div>
    <% end %>
  </div>
</div>