config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users
  root to: 'pages#home'
  resources :profiles, only: [:index, :show, :new, :edit, :update] do
    resources :notes, only: [:new, :create, :show, :index]
  end
  resources :loans, only: [:new, :create, :show, :index] do
    resources :loanees, only: [:new, :create]
  end
  resources :loanees, only: [:show, :edit, :update] do
    resources :weekly_payments, only: [:new, :create, :index, :edit, :update]
  end
  resources :users, only: [:new, :index, :show]
  resources :weekly_payments, only: [:edit, :update]
  post 'user_profile', to: "users#create", as: 'user_profile'
end

app/models/weekly_payment.rb
class WeeklyPayment < ApplicationRecord
  belongs_to :loanee

  validates :amount, presence: true
  # monetize :amount_cents
  def amount_money
    Money.new(amount, :mxn)
  end
end

app/controllers/weekly_payments_controller.rb
class WeeklyPaymentsController < ApplicationController
  def index
    @weekly_payments = policy_scope(WeeklyPayment)
    @loanee = Loanee.find(params[:loanee_id])
    past_payments = 0
    @loanee.weekly_payments.each do |payment|
      past_payments += payment.amount.to_f
    end
    @progress = past_payments/@loanee.total.to_f * 100
  end

  def new
    @loanee = Loanee.find(params[:loanee_id])
    @weekly_payment = WeeklyPayment.new
    authorize @weekly_payment
  end

  def create
    @loanee = Loanee.find(params[:loanee_id])
    @weekly_payment = WeeklyPayment.new(weekly_payment_params)
    @weekly_payment.loanee = @loanee
    authorize @weekly_payment
    if @weekly_payment.save
      redirect_to loanee_weekly_payments_path
    else
      render :new
    end
  end

  def edit
    @weekly_payment = WeeklyPayment.find(params[:id])
    @loanee = @weekly_payment.loanee
    authorize @weekly_payment
  end

  def update
    @weekly_payment = WeeklyPayment.find(params[:id])
    @loanee = Loanee.find(params[:loanee_id])
    @weekly_payment.update(weekly_payment_params)
    @weekly_payment.loanee = @loanee
    authorize @weekly_payment
    if @weekly_payment.save
      redirect_to loanee_weekly_payments_path()
    else
      render :edit
    end
  end

  private

  def weekly_payment_params
    params.require(:weekly_payment).permit(:loanee_id, :amount, :amount_cents)
  end
end

app/views/weekly_payments/_chart.html.erb
<% unless user.active_debt.nil? %>
<%= pie_chart user.payment_ratio, library: { pieSliceText: 'value' }, colors: ["#FCD581", "#5A7C98"], donut: true%>
<% end %>

app/views/weekly_payments/_form.html.erb
<%= simple_form_for [@loanee, @weekly_payment] do |f| %>
  <%= f.input :amount, input_html: { min: '0', step: 'any' }, label: 'Enter amount' %>
  <%= f.submit "Edit Payment", data: {confirm: "Are you sure this information is correct?"}, class: "btn btn-primary" %>
<% end %>

app/views/weekly_payments/_form_edit.html.erb
<%= simple_form_for [@loanee, @weekly_payment] do |f| %>
  <%= f.input :amount, input_html: { min: '0', step: 'any' }, label: 'Edit amount' %>
  <%= f.submit "Edit Payment", data: {confirm: "Are you sure this information is correct?"}, class: "btn btn-primary" %>
<% end %>

app/views/weekly_payments/_next_payment.html.erb
  <% i = 1 %>
<% @loanee.weekly_payments.order(created_at: :asc).each do |weekly_payment| %>
  <% i += 1 %>
<% end %>
<% rest = @loanee.loan.weeks - @loanee.weekly_payments.count %>
<%= ((@loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') %>

app/views/weekly_payments/_payment_schedule.html.erb
<div class="row d-flex justify-content-center">
  <% i = 1 %>
  <% @loanee.weekly_payments.order(created_at: :asc).each do |weekly_payment| %>
    <%if ((@loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') == weekly_payment.created_at.strftime('%y-%m-%d') && @loanee.user.get_weeklypayment > weekly_payment.amount.to_f %>
      <div class="date-card col-md-2 m-2 rounded" style="background-color:#F5F5F5"><%= ((@loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') %> <i class="fas fa-exclamation-circle" style="color:#FCD581; font-size:12px;"></i></div>
    <% else ((@loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') == weekly_payment.created_at.strftime('%y-%m-%d') && @loanee.user.get_weeklypayment <= weekly_payment.amount.to_f%>
      <div class="date-card col-md-2 m-2 rounded" style="background-color:#F5F5F5"><%= ((@loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') %> <i class="fas fa-check-square" style="color:#4F926E; font-size:12px;"></i></div>
      <% i += 1 %>
    <% end %>
  <% end %>
  <% rest = @loanee.loan.weeks - @loanee.weekly_payments.count %>
  <div class="date-card col-md-2 m-2 rounded" style="background-color:#DD7373;color:white;"><%= ((@loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') %></div>
  <% i += 1 %>
  <% (rest-1).times do |weekly_payment| %>
    <div class="date-card col-md-2 m-2 rounded" style="background-color:#F5F5F5"><%= ((@loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') %></div>
    <% i += 1 %>
  <% end %>
</div>

app/views/weekly_payments/_table.html.erb
<table class="table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Payment Received</th>
      <%# <th scope="col">Weekly Payment Amount</th> %>
      <th scope="col">Remaining Amount</th>
      <th scope="col">Payment Date</th>
      <th scope="col">Payment Expected Date</th>
      <th scope="col">Edit Payment</th>
    </tr>
  </thead>
  <tbody>
    <% i = 1 %>
    <% remainder = @loanee.total.to_f%>

    <% @loanee.weekly_payments.order(created_at: :asc ).each do |weekly_payment|%>
      <% if remainder - weekly_payment.amount.to_f < 0 %>
        <tr class="overpay">
          <th scope="row">Over Paid</th>
          <td ><%= weekly_payment.amount.to_f.round(2) %></td>
          <%# <td><%= (weekly_payment.loanee.total / weekly_payment.loanee.loan.weeks).round(2) %>
          <td><%= remainder - weekly_payment.amount.to_f.round(2) %></td>
          <td><%= weekly_payment.created_at.strftime("%B %e %Y") %></td>
          <td><%= ((@loanee.loan.start_date) + (i * 7)).strftime("%B %e %Y") %></td>
          <td><%= link_to edit_loanee_weekly_payment_path(weekly_payment.loanee_id, weekly_payment) do%>
              <i class="fas fa-edit"></i>
            <% end %>
          </td>
        </tr>
        <% i += 1 %>
        <% remainder -= weekly_payment.amount.to_f %>
      <% else %>
        <tr>
          <th scope="row"><%= i %></th>
          <td><%= weekly_payment.amount.to_f.round(2) %></td>
          <%# <td><%= (weekly_payment.loanee.total / weekly_payment.loanee.loan.weeks).round(2) %>
          <td><%= remainder - weekly_payment.amount.to_f.round(2) %></td>
          <td><%= weekly_payment.created_at.strftime("%B %e %Y")%></td>
          <td><%= ((@loanee.loan.start_date) + (i * 7)).strftime("%B %e %Y")%></td>
          <td><%= link_to edit_loanee_weekly_payment_path(weekly_payment.loanee_id, weekly_payment) do%>
              <i class="fas fa-edit"></i>
            <% end %>
          </td>
        </tr>
        <% i += 1 %>
        <% remainder -= weekly_payment.amount.to_f.round(2) %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/weekly_payments/edit.html.erb
<div class="container" style="text-align:center;">
  <h1>Edit payment</h1>
  <br>
  <h2><%= @loanee.user.full_name.titleize %> paid <%= @weekly_payment.amount.to_f.round(2) %> on <%= @weekly_payment.created_at.strftime("%A %B %d %Y") %>
    <br>
    <%= render 'form_edit', loanee:@loanee%>
    <%= link_to profile_path(@loanee.user.profile) do%>
      <p style="text-align:left;"><i class="fas fa-long-arrow-alt-left fa-2x"></i></p>
    <% end %>
  </div>

app/views/weekly_payments/index.html.erb
<div class="container">
  <div class="card-profile">
    <h1><%= @loanee.user.first_name %>'s Weekly Payment Information</h1>
    <br>
    <div class="row d-flex justify-content-around align-items-end">
      <div>
        <%= render 'chart', user:@loanee.user%>
        <p style="text-align:center;"><strong>Loan Repayment Chart</strong></p>
      </div>
      <div>
        <p><i class="fas fa-money-check"></i> Loan#: <strong><i>100<%= link_to @loanee.loan.id, loan_path(@loanee.loan) %></i></strong></p>
        <p><i class="fas fa-calendar-day"></i> Loan Start Date: <strong><i><%= @loanee.loan.start_date %></i></strong></p>
        <p><i class="fas fa-user-clock"></i> Duration: <strong><i><%= @loanee.loan.weeks %></i></strong> weeks</p>
        <p><i class="fas fa-coins"></i> Loan Total: $<strong><i><%= @loanee.total.to_f.round(2) %></i></strong></p>
        <p><i class="fas fa-comment-dollar"></i> Weekly Payment Amount: $<strong><i><%= @loanee.user.get_weeklypayment.round(2) %></i></strong></p>
      </div>
    </div>
    <br>
    <% if @loanee.weekly_payments.any?%>
      <div style="text-align: center;">
        <br>
        <%= render 'table', loanee:@loanee %>
        <br>
        <br>
        <p style="text-align:center;">Next payment for <%= @loanee.user.first_name %> is due on <i><%= render 'next_payment', loanee:@loanee %></i></p>
        <div> <%= render 'payment_schedule', loanee:@loanee %></div>
      </div>
    <% else %>
      <p class="mark-yellow"><%= @loanee.user.full_name.titleize %> has not made any repayments yet.</p>
    <% end %>
    <%= link_to profile_path(@loanee.user.profile) do%>
      <p><i class="fas fa-long-arrow-alt-left fa-2x"></i></p>
    <% end %>
  </div>
</div>

app/views/weekly_payments/new.html.erb
<div class="container" style="text-align:center;">
  <h1>Receive payment</h1>
  <br>
  <h2>Weekly payment for <%= @loanee.user.full_name.titleize %> is <strong style="color:red;">$<%= (@loanee.total.to_f.round(2) / @loanee.loan.weeks).round(2) %></strong></h2>
  <%= render 'form', loanee:@loanee%>
  <%= link_to profile_path(@loanee.user.profile) do%>
    <p style="text-align:left;"><i class="fas fa-long-arrow-alt-left fa-2x"></i></p>
  <% end %>
</div>