config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users
  root to: 'pages#home'
  resources :profiles, only: [:index, :show, :new, :edit, :update] do
    resources :notes, only: [:new, :create, :show, :index]
  end
  resources :loans, only: [:new, :create, :show, :index] do
    resources :loanees, only: [:new, :create]
  end
  resources :loanees, only: [:show, :edit, :update] do
    resources :weekly_payments, only: [:new, :create, :index, :edit, :update]
  end
  resources :users, only: [:new, :index, :show]
  resources :weekly_payments, only: [:edit, :update]
  post 'user_profile', to: "users#create", as: 'user_profile'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :loans # loan officer
  has_many :loanees, through: :loans
  has_many :debts, class_name: 'Loanee' # borrower
  has_one :loan_groups, through: :loanees, source: :loans
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def to_label
    full_name
  end

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def active_debt
    debts.first
  end

  def percentage
    (get_payments_amount.to_f * 100 / get_total.to_f)
  end

  def payment_ratio
    # [['Task', 'Hours per Day'],
    [['Paid', get_payments_amount.to_f],
    ['Not paid', (get_total.to_f - get_payments_amount.to_f)]]
  end

  def payment_ratio_group
    # [['Task', 'Hours per Day'],
    [['Paid', get_payments_amount_group.to_f],
    ['Not paid', get_total_group.to_f - get_payments_amount_group.to_f]]
  end

  def weekly_payment_graph
    data_format = []
    unless active_debt.nil?
      debts.last.weekly_payments.each do |payment|
        data_format << [payment.created_at.strftime("%B %d %Y"), payment.amount.to_f]
      end
    else
      return data_format
    end
    return data_format
  end

  def get_payments_amount
    payments_amount = 0
    unless active_debt.nil?
      debts.last.weekly_payments.each do |payment|
        payments_amount += payment.amount.to_f
      end
    else
      return payments_amount
    end
    return payments_amount
  end

  def get_total
    unless active_debt.nil?
      debts.last.total.to_f
    else
      return 0
    end
  end

  def get_payments_amount_group
    payments_amount_group = 0
    unless active_debt.nil?
      debts.last.loan.loanees.each do |loanee|
        loanee.weekly_payments.each do |payment|
          payments_amount_group += payment.amount.to_f
        end
      end
    else
      return payments_amount_group
    end
    return payments_amount_group
  end

  def get_total_group
    total = 0
    unless active_debt.nil?
      debts.last.loan.loanees.each do |loanee|
        total += loanee.total.to_f
      end
    else
      return total
    end
    return total
  end

  def multiple_chart
    format_arr = []
    debts.last.loan.loanees.each do |loanee|
      data_arr = []
      loanee.weekly_payments.each do |payment|
        data_arr << ["#{payment.created_at.strftime("%B %d")}", payment.amount.to_f]
      end
      format_arr << {:name=>"#{loanee.user.first_name}", :data=>data_arr}
    end
    return format_arr

    #      return  [
    #   {:name=>"Golden State Warriors", :data=>[["2016-11-19T17:42:18.699Z", 0.6622516556291391], ["2016-11-20T07:56:55.662Z", 0.6622516556291391]]},
    #   {:name=>"Los Angeles Clippers", :data=>[["2016-11-19T17:42:18.795Z", 0.1], ["2016-11-20T07:56:55.717Z", 0.1]]}
    # ]
  end

  def get_weeklypayment
    debts.last.total.to_f / debts.last.loan.weeks
  end


  include PgSearch::Model
  pg_search_scope :loan_search,
    against: [ :first_name, :last_name, :email],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  # skip_before_action :require_no_authentication
  # before_action :authenticate_user!

  # def new
  #   @user = User.new
  #   @user.build_profile
  #   authorize @user
  # end

  # private

  # def user_params
  #   params.require(:user).permit(:email, :password, :first_name, :last_name, profile_attributes: [:village, :phone_number, :birthday, :join_date, :business_type])
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  def index
    if params[:query].present?
      @users = policy_scope(User).loan_search(params[:query])
    else
      @users = User.all
      @users = policy_scope(User)
    end
  end

  def new
    @user = User.new
    @user.build_profile
    authorize @user
  end

  def show
    @payments_amount = @user.get_payments_amount
    @total = @user.get_total
    @data = [@payments, @total]
  end

  def create
    @user = User.new(user_params)
    authorize @user

    if @user.save
      redirect_to profiles_path
    else
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, profile_attributes: [:village, :phone_number, :birthday, :join_date, :business_type, :birthday, :photo])
  end

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  # def get_payments_amount(user)
  #   payments_amount = 0
  #   unless user.active_debt.nil?
  #     user.active_debt.weekly_payments.each do |payment|
  #       payments_amount += payment.amount
  #     end
  #   else
  #     return payments_amount
  #   end
  #   return payments_amount
  # end

  # def get_total(user)
  #   unless user.active_debt.nil?
  #     user.active_debt.total
  #   else
  #     return 0
  #   end
  # end
end

app/views/users/_graph.html.erb
<% unless user.active_debt.nil? %>
<%= line_chart user.multiple_chart, colors: ["#5A7C98","#FCD581","#73E2A7","#DD7373","#061826"]%>
<% end %>

app/views/users/_group_chart.html.erb
<% unless user.active_debt.nil? %>
<% user.active_debt.loan%>
<%= pie_chart user.payment_ratio_group, library: { pieSliceText: 'value' }, colors: ["#FCD581", "#5A7C98"], donut: true%>
<% end %>

app/views/users/_individual_chart.html.erb
<% unless user.active_debt.nil? %>
<%= pie_chart user.payment_ratio, library: { pieSliceText: 'value' }, colors: ["#FCD581","#5A7C98"], donut: true%>
<% end %>

app/views/users/_next_payment.html.erb
  <% i = 1 %>
<% @user.debts.last.weekly_payments.order(created_at: :asc).each do |weekly_payment| %>
  <% i += 1 %>
<% end %>
<% rest = @user.debts.last.loan.weeks - @user.debts.last.weekly_payments.count %>
<%= ((@user.debts.last.loan.start_date) + (i * 7)).strftime('%y-%m-%d') %>

app/views/users/_progress.html.erb
<% user.debts.last.loan.loanees.each do |loanee|%>
  <p><%= loanee.user.first_name%><div class="progress"></p>
    <div class="progress-bar progress-bar-striped" role="progressbar" style="width: <%= loanee.user.percentage %>%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"><%= loanee.user.percentage.round(2) %>%</div>
  </div>
  <br>
<% end %>

app/views/users/_schedule.html.erb
<div class="row d-flex justify-content-center">
  <% i = 1 %>
    <% loanee.weekly_payments.order(created_at: :asc).each do |weekly_payment| %>
      <%if ((loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') == weekly_payment.created_at.strftime('%y-%m-%d') && loanee.user.get_weeklypayment > weekly_payment.amount.to_f %>
        <div class="date-card col-md-2 m-2 rounded" style="background-color:#F5F5F5"><%= ((loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') %> <i class="fas fa-exclamation-circle" style="color:#FCD581; font-size:12px;"></i></div>
      <% else ((loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') == weekly_payment.created_at.strftime('%y-%m-%d') && loanee.user.get_weeklypayment <= weekly_payment.amount.to_f%>
        <div class="date-card col-md-2 m-2 rounded" style="background-color:#F5F5F5"><%= ((loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') %> <i class="fas fa-check-square" style="color:#73E2A7; font-size:12px;"></i></div>
        <% i += 1 %>
      <% end %>
    <% end %>
    <% rest = loanee.loan.weeks - loanee.weekly_payments.count %>
    <div class="date-card col-md-2 m-2 rounded" style="background-color:#DD7373;color:white;"><%= ((loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') %></div>
    <% i += 1 %>
    <% (rest-1).times do |weekly_payment| %>
      <div class="date-card col-md-2 m-2 rounded" style="background-color:#F5F5F5"><%= ((loanee.loan.start_date) + (i * 7)).strftime('%y-%m-%d') %></div>
      <% i += 1 %>
    <% end %>
</div>

app/views/users/_search.html.erb
<%= simple_form_for :query, url: users_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="query" id="search_query" placeholder="Enter Name" />
    <button name="button" type="submit" class="btn btn-search">
      <i class="fas fa-search"></i> Loan Search
    </button>
  </div>
<% end %>

app/views/users/_search_results.html.erb
<div class="row align-items-start mb-2" data-refresh-list-target="list">
  <% users.each do |user| %>
    <% if user.debts.any?%>
      <% user.debts.each do |debt| %>
        <div class="col-sm-4">
          <% img_list = ["https://cdn.pixabay.com/photo/2020/10/30/08/56/money-5698019_1280.png", "https://images.pexels.com/photos/5849563/pexels-photo-5849563.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260", "https://images.pexels.com/photos/5466806/pexels-photo-5466806.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260", "https://images.pexels.com/photos/210990/pexels-photo-210990.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"]%>
          <div class="card-identity" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= "#{img_list.sample}"%>)">
            <div class="card-identity-content">
              <%= link_to '', loan_path(debt.loan), class: 'card-link' %>
              <h3 class="card-village">Loan ID <%= debt.loan.id%></h2>
              <h3 class="card-name">Start Date <%= debt.loan.start_date%></h2>
              <h2 class="card-name"><%= user.full_name.titleize %></h2>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <%= render 'search'%>
  <%= render 'search_results', users:@users%>
</div>

app/views/users/new.html.erb
<div class="container my-4 pb-4">
  <h1 style="margin-bottom: 24px">Create a profile</h1>
  <%= simple_form_for @user, url: user_profile_path do |f| %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.simple_fields_for :profile do |profile_form| %>
      <%= profile_form.input :village %>
      <%= profile_form.input :birthday, start_year: Date.today.year - 110, end_year: Date.today.year%>
      <%= profile_form.input :phone_number %>
      <%= profile_form.input :join_date, start_year: Date.today.year - 11, end_year: Date.today.year %>
      <%= profile_form.input :business_type %>
      <%= profile_form.input :photo, as: :file %>
    <% end %>
    <%= f.submit class: "btn btn-large" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="card-profile">
    <h1>Hello <%= @user.first_name%>!</h1>
    <br>
    <div class="row d-flex justify-content-around">
      <div>
        <h3 style="text-align:center;"><%= @user.first_name%>'s payment chart</h3>
        <%= render 'individual_chart', user:@user%>
      </div>
      <div>
        <h3 style="text-align:center;">Group payment chart</h3>
        <%= render 'group_chart', user:@user%>
      </div>
    </div>
    <br>
    <br>
    <br>
    <p style="text-align:center;">Your next paymet is sheduled on: <strong style="color:#DD7373;"><%= render 'next_payment', user:@user, payments_amount:@payments_amount%></strong></p>
    <%= render 'schedule', loanee:@user.debts.last%>
    <br>
    <br>
    <br>
    <h3 style="text-align:center;">Group Weekly Payments</h3>
    <%= render 'graph', user:@user%>
    <br>
    <br>
    <br>
    <br>
    <br>
      <h3 style="text-align:center;">Individual progress</h3>
      <%= render 'progress', user:@user%>
  </div>
</div>