config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users
  root to: 'pages#home'
  resources :profiles, only: [:index, :show, :new, :edit, :update] do
    resources :notes, only: [:new, :create, :show, :index]
  end
  resources :loans, only: [:new, :create, :show, :index] do
    resources :loanees, only: [:new, :create]
  end
  resources :loanees, only: [:show, :edit, :update] do
    resources :weekly_payments, only: [:new, :create, :index, :edit, :update]
  end
  resources :users, only: [:new, :index, :show]
  resources :weekly_payments, only: [:edit, :update]
  post 'user_profile', to: "users#create", as: 'user_profile'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_index_status.html.erb
<% unless profile.user.debts == []  %>
  <% case profile.user.debts.last
.status
           when 'active' %>
  <i class="fas fa-check-circle" style="color: #309C76"></i>
  <% when 'closed' %>
  <i class="fas fa-check-circle" style="color: #B7B5B3"></i>
  <% when 'default' %>
  <i class="fas fa-times-circle" style="color: #F71735"></i>
  <% when 'late' %>
  <i class="fas fa-clock" style="color: #F5F749"></i>
<% end %>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-theblender mb-3">
  <%= link_to root_path, class: "navbar-brand px-3" do %>
    <%= image_tag("envia_white.png") %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <nav>
    <ul class="navbar-nav mr-auto px-3">
      <% if user_signed_in? && current_user.profile.nil?%>
        <!-- -->
        <li>
          <%= link_to loans_path do %>
            <i class="fas fa-tachometer-alt fa-2x"></i>
          <% end %>
        </li>
        <li>
          <%= link_to new_loan_path do %>
            <i class="fas fa-file-invoice-dollar fa-2x"></i>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_path do %>
            <i class="fas fa-user-plus fa-2x"></i>
          <% end %>
        </li>
        <li>
          <%= link_to profiles_path do %>
            <i class="fas fa-search fa-2x"></i>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt fa-2x"></i>
          <% end %>
        </li>
      <% elsif user_signed_in? && current_user.profile.nil? == false %>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt fa-2x"></i>
          <% end %>
        </li>
        <!-- -->
      <% else%>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do %>
            <i class="fas fa-sign-in-alt fa-2x"></i>
          <% end %>
        <% end %>
      </ul>
    </nav>
  </div>

app/views/shared/temp_file.erb
<div class="container">
  <div class="card-dashboard-header">
    <% expected_amount_total = 0 %>
    <% actual_amount_total = 0 %>
    <div class="card-title-dash">
      <h1>Today is <%= Date.today.strftime("%A %B %d %Y") %></h1>
    </div>
  </div>
  <% @loans.each do |loan| %>
    <% i = 1 %>
    <% payments_today= [] %>
    <% loan.weeks.times do %>
      <%if ((loan.start_date) + (i * 7)) == Date.today%>
        <p><% payments_today << ((loan.start_date) + (i * 7))%></p>
        <% i = i + 1%>
      <% end %>
    <% end %>
    <% payments_today.each do |payment_day| %>
      <div class="card-dashboard-body">
        <p>Loan id: <%= link_to loan.id, loan_path(loan) %></p>
        <h3><%= loan.loanees.first.user.profile.village %></h3>
        <% expected_amount_group = 0 %>
        <% actual_amount_group = 0 %>
        <div class="d-flex justify-content-around align-items-center p-3">
          <%loan.loanees.each do |loanee| %>
            <%= cl_image_tag(loanee.user.profile.photo.key, :transformation=>[
            {:gravity=>"face", :height=>80, :width=>80, :crop=>"fill"}, {:radius=>"max"}]) %>
            <%= loanee.user.full_name.titleize %>
            <% expected_amount_group= expected_amount_group + (loanee.total.to_f.round(2) / loan.weeks) %>
            <%loanee.weekly_payments.each do |weekly_payment| %>
              <%if weekly_payment.created_at.strftime('%Y-%m-%d') == Date.today.strftime('%Y-%m-%d')%>
                <% actual_amount_group= actual_amount_group + weekly_payment.amount.to_f.round(2)%>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="d-flex" justify-content-around>
          expected_amount_group == 0 %>
          <p>You collected $ <%= actual_amount_group %> out of  $ <%= expected_amount_group.round %> from this group</p>
        <% end %>
        <% unless %>
          <% expected_amount_total= expected_amount_total + expected_amount_group %>
          <% actual_amount_total= actual_amount_total + actual_amount_group %>
        </div>
      </div>
      <hr>
    <% end %>
  <% end %>
  <div class="d-flex justify-content-around">
    <div class="card-info-dash">
      <h2>You actually collected $ <%= actual_amount_total.round%></h2>
    </div>
    <div class="card-info-dash">
      <h2>You are expected to collect $ <%= expected_amount_total.round %> </h2>
    </div>
  </div>
</div>